image: "rust:slim"

stages:
  - check
  - build

# Variable defaults
variables:
  RUST_VERSION: beta

# # Cargo artifacts caching per Rust version and pipeline
# cache:
#   key: "$RUST_VERSION"
#   paths:
#     - /usr/local/rustup/
#     - /usr/local/cargo/
#     - target/

# Install the proper Rust compiler version
before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends build-essential pkg-config libssl-dev default-libmysqlclient-dev libleptonica-dev libtesseract-dev tesseract-ocr-eng clang
  - |
    rustup install $RUST_VERSION
    rustup default $RUST_VERSION
  - |
    rustc --version
    cargo --version

# Check on stable, beta and nightly 
.check-base: &check-base
  stage: check
  script:
    - cargo check --verbose
    - cargo check --verbose --no-default-features
    - cargo check --verbose --no-default-features --features ffmpeg
    - cargo check --verbose --no-default-features --features ocr
    - cargo test --verbose
# check-stable:
#   <<: *check-base
#   variables:
#     RUST_VERSION: stable
check-beta:
  <<: *check-base
  variables:
    RUST_VERSION: beta
check-nightly:
  <<: *check-base
  variables:
    RUST_VERSION: nightly

# Build using Rust stable
build:
  stage: build
  needs:
    - check-nightly
  script:
    - cargo build --release --verbose
