[package]
name = "ban-binance-bot"
version = "0.1.0"
authors = ["timvisee <tim@visee.me>"]
edition = "2018"

[dependencies]
dotenv = "0.14"
futures = "0.1"
lazy_static = "1.4"
linkify = "0.4"
reqwest = "0.9"
tokio-core = "0.1"
tokio-signal = "0.2"
url = "1.2"

# Use a specific version with patched Telegram bot API
[dependencies.telegram-bot]
version = "*"
git = "https://github.com/telegram-rs/telegram-bot"
rev = "d82b179"
